# Var-value pairs needed in partcomp 2-step flow.
VCS_PC2_VARS =

ifndef MAKEPROF
VLOGAN = ${VCS_PC2_VARS} ${VCS_HOME}/bin/vlogan
VCS = ${VCS_PC2_VARS} ${VCS_HOME}/bin/vcs
else
VLOGAN = ${VCS_PC2_VARS} /usr/bin/time -f "MAKEPROF@$@, Real: %e, User: %U, Sys: %S " ${VCS_HOME}/bin/vlogan
VCS = ${VCS_PC2_VARS} /usr/bin/time -f "MAKEPROF@$@, Real: %e, User: %U, Sys: %S " ${VCS_HOME}/bin/vcs
endif

VCS_OPTIONS =  -mx_invoke_vcs_from_tool -mxunielab     -file /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/rkv_i2c_tb.simv.daidir/.partcomp_options -partcomp_master_daidir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/rkv_i2c_tb.simv.daidir   -q    -assert enable_hier   -full64    -cm_dir out/obj/rkv_i2c_tb.simv.vdb  -cm implAssert  -q  

VCS_STITCH_OPTIONS =    -file /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/rkv_i2c_tb.simv.daidir/.partcomp_stitch_options -Xpiyushb1=0x80 -sverilog  -full64     -cm implAssert  

vl_pcs : PARTCOMP_SIMV

/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_msglog_z2c7Ib/libvcspc__vcs_msglog_z2c7Ib.so : /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_msglog_z2c7Ib/.touched
	/bin/rm -rf /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_msglog_z2c7Ib/libvcspc__vcs_msglog_z2c7Ib.so.daidir/ar.lst
	${VCS} ${PARTCOMP_ADD_VCS_OPT} ${VCS_OPTIONS}   -partcomp=so -partcomp_so_dir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_msglog_z2c7Ib VCS_PARTCOMP_LIB.pc__vcs_msglog_config -o $@ -Mdir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_msglog_z2c7Ib/csrc  -Xarijit=0x2 -sverilog   -l /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_msglog_z2c7Ib/_vcs_msglog_z2c7Ib.log 

/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/rkv_i2c_tb_Rr2Nhb/libvcspc_rkv_i2c_tb_Rr2Nhb.so : /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/rkv_i2c_tb_Rr2Nhb/.touched
	/bin/rm -rf /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/rkv_i2c_tb_Rr2Nhb/libvcspc_rkv_i2c_tb_Rr2Nhb.so.daidir/ar.lst
	${VCS} ${PARTCOMP_ADD_VCS_OPT} ${VCS_OPTIONS}   -partcomp=so -partcomp_so_dir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/rkv_i2c_tb_Rr2Nhb VCS_PARTCOMP_LIB.pc_rkv_i2c_tb_config -o $@ -Mdir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/rkv_i2c_tb_Rr2Nhb/csrc  -Xarijit=0x2 -sverilog   -l /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/rkv_i2c_tb_Rr2Nhb/rkv_i2c_tb_Rr2Nhb.log 

/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/uvm_custom_install_recording_2yENJb/libvcspc_uvm_custom_install_recording_2yENJb.so : /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/uvm_custom_install_recording_2yENJb/.touched
	/bin/rm -rf /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/uvm_custom_install_recording_2yENJb/libvcspc_uvm_custom_install_recording_2yENJb.so.daidir/ar.lst
	${VCS} ${PARTCOMP_ADD_VCS_OPT} ${VCS_OPTIONS}   -partcomp=so -partcomp_so_dir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/uvm_custom_install_recording_2yENJb VCS_PARTCOMP_LIB.pc_uvm_custom_install_recording_config -o $@ -Mdir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/uvm_custom_install_recording_2yENJb/csrc  -Xarijit=0x2 -sverilog   -l /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/uvm_custom_install_recording_2yENJb/uvm_custom_install_recording_2yENJb.log 

/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_SNPS_VCS_intf_repository/libvcspc__SNPS_VCS_intf_repository.so : /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_SNPS_VCS_intf_repository/.touched
	/bin/rm -rf /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_SNPS_VCS_intf_repository/libvcspc__SNPS_VCS_intf_repository.so.daidir/ar.lst
	${VCS} ${PARTCOMP_ADD_VCS_OPT} ${VCS_OPTIONS}   -partcomp=so -partcomp_so_dir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_SNPS_VCS_intf_repository VCS_PARTCOMP_LIB.pc__SNPS_VCS_intf_repository_config -o $@ -Mdir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_SNPS_VCS_intf_repository/csrc  -Xarijit=0x2 -sverilog   -l /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_SNPS_VCS_intf_repository/_SNPS_VCS_intf_repository.log 

/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_pc_package__TpDXPd/libvcspc__vcs_pc_package__TpDXPd.so : /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_pc_package__TpDXPd/.touched
	/bin/rm -rf /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_pc_package__TpDXPd/libvcspc__vcs_pc_package__TpDXPd.so.daidir/ar.lst
	${VCS} ${PARTCOMP_ADD_VCS_OPT} ${VCS_OPTIONS}   -partcomp=so -partcomp_so_dir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_pc_package__TpDXPd VCS_PARTCOMP_LIB.pc__vcs_pc_package__config -o $@ -Mdir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_pc_package__TpDXPd/csrc  -Xarijit=0x2 -sverilog   -l /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_pc_package__TpDXPd/_vcs_pc_package__TpDXPd.log 

PARTCOMP_SIMV : /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_msglog_z2c7Ib/libvcspc__vcs_msglog_z2c7Ib.so /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/rkv_i2c_tb_Rr2Nhb/libvcspc_rkv_i2c_tb_Rr2Nhb.so /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/uvm_custom_install_recording_2yENJb/libvcspc_uvm_custom_install_recording_2yENJb.so /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_SNPS_VCS_intf_repository/libvcspc__SNPS_VCS_intf_repository.so /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_pc_package__TpDXPd/libvcspc__vcs_pc_package__TpDXPd.so 
	${VCS}  -partcomp=stitch ${VCS_STITCH_OPTIONS} -file /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/rkv_i2c_tb.simv.daidir/.stitch_so_list -o out/obj/rkv_i2c_tb.simv csrc/topshell_partcomp.v 


	@echo Done Verilog partition compilations

