# Var-value pairs needed in partcomp 2-step flow.
VCS_PC2_VARS =

ifndef MAKEPROF
VLOGAN = ${VCS_PC2_VARS} ${VCS_HOME}/bin/vlogan
VCS = ${VCS_PC2_VARS} ${VCS_HOME}/bin/vcs
else
VLOGAN = ${VCS_PC2_VARS} /usr/bin/time -f "MAKEPROF@$@, Real: %e, User: %U, Sys: %S " ${VCS_HOME}/bin/vlogan
VCS = ${VCS_PC2_VARS} /usr/bin/time -f "MAKEPROF@$@, Real: %e, User: %U, Sys: %S " ${VCS_HOME}/bin/vcs
endif

VCS_OPTIONS =  -mx_invoke_vcs_from_tool -mxunielab     -file /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/rkv_i2c_tb.simv.daidir/.partcomp_options -partcomp_master_daidir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/rkv_i2c_tb.simv.daidir   -q    -assert enable_hier   -full64    -cm_dir out/obj/rkv_i2c_tb.simv.vdb  -cm implAssert  -q  

VCS_STITCH_OPTIONS =    -file /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/rkv_i2c_tb.simv.daidir/.partcomp_stitch_options -Xpiyushb1=0x80 -sverilog  -full64     -cm implAssert  

vl_pcs : PARTCOMP_SIMV

/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_msglog_UF52ed/libvcspc__vcs_msglog_UF52ed.so : /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_msglog_UF52ed/.touched
	/bin/rm -rf /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_msglog_UF52ed/libvcspc__vcs_msglog_UF52ed.so.daidir/ar.lst
	${VCS} ${PARTCOMP_ADD_VCS_OPT} ${VCS_OPTIONS}   -partcomp=so -partcomp_so_dir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_msglog_UF52ed VCS_PARTCOMP_LIB.pc__vcs_msglog_config -o $@ -Mdir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_msglog_UF52ed/csrc  -Xarijit=0x2 -sverilog   -l /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_msglog_UF52ed/_vcs_msglog_UF52ed.log 

/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/rkv_i2c_tb_67wvne/libvcspc_rkv_i2c_tb_67wvne.so : /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/rkv_i2c_tb_67wvne/.touched
	/bin/rm -rf /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/rkv_i2c_tb_67wvne/libvcspc_rkv_i2c_tb_67wvne.so.daidir/ar.lst
	${VCS} ${PARTCOMP_ADD_VCS_OPT} ${VCS_OPTIONS}   -partcomp=so -partcomp_so_dir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/rkv_i2c_tb_67wvne VCS_PARTCOMP_LIB.pc_rkv_i2c_tb_config -o $@ -Mdir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/rkv_i2c_tb_67wvne/csrc  -Xarijit=0x2 -sverilog   -l /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/rkv_i2c_tb_67wvne/rkv_i2c_tb_67wvne.log 

/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/uvm_custom_install_recording_87QqAb/libvcspc_uvm_custom_install_recording_87QqAb.so : /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/uvm_custom_install_recording_87QqAb/.touched
	/bin/rm -rf /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/uvm_custom_install_recording_87QqAb/libvcspc_uvm_custom_install_recording_87QqAb.so.daidir/ar.lst
	${VCS} ${PARTCOMP_ADD_VCS_OPT} ${VCS_OPTIONS}   -partcomp=so -partcomp_so_dir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/uvm_custom_install_recording_87QqAb VCS_PARTCOMP_LIB.pc_uvm_custom_install_recording_config -o $@ -Mdir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/uvm_custom_install_recording_87QqAb/csrc  -Xarijit=0x2 -sverilog   -l /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/uvm_custom_install_recording_87QqAb/uvm_custom_install_recording_87QqAb.log 

/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_SNPS_VCS_intf_repository/libvcspc__SNPS_VCS_intf_repository.so : /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_SNPS_VCS_intf_repository/.touched
	/bin/rm -rf /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_SNPS_VCS_intf_repository/libvcspc__SNPS_VCS_intf_repository.so.daidir/ar.lst
	${VCS} ${PARTCOMP_ADD_VCS_OPT} ${VCS_OPTIONS}   -partcomp=so -partcomp_so_dir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_SNPS_VCS_intf_repository VCS_PARTCOMP_LIB.pc__SNPS_VCS_intf_repository_config -o $@ -Mdir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_SNPS_VCS_intf_repository/csrc  -Xarijit=0x2 -sverilog   -l /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_SNPS_VCS_intf_repository/_SNPS_VCS_intf_repository.log 

/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_pc_package__h66j1c/libvcspc__vcs_pc_package__h66j1c.so : /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_pc_package__h66j1c/.touched
	/bin/rm -rf /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_pc_package__h66j1c/libvcspc__vcs_pc_package__h66j1c.so.daidir/ar.lst
	${VCS} ${PARTCOMP_ADD_VCS_OPT} ${VCS_OPTIONS}   -partcomp=so -partcomp_so_dir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_pc_package__h66j1c VCS_PARTCOMP_LIB.pc__vcs_pc_package__config -o $@ -Mdir=/home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_pc_package__h66j1c/csrc  -Xarijit=0x2 -sverilog   -l /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_pc_package__h66j1c/_vcs_pc_package__h66j1c.log 

PARTCOMP_SIMV : /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_msglog_UF52ed/libvcspc__vcs_msglog_UF52ed.so /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/rkv_i2c_tb_67wvne/libvcspc_rkv_i2c_tb_67wvne.so /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/uvm_custom_install_recording_87QqAb/libvcspc_uvm_custom_install_recording_87QqAb.so /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_SNPS_VCS_intf_repository/libvcspc__SNPS_VCS_intf_repository.so /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/partitionlib/_vcs_pc_package__h66j1c/libvcspc__vcs_pc_package__h66j1c.so 
	${VCS}  -partcomp=stitch ${VCS_STITCH_OPTIONS} -file /home/verifier/DVT_Code/APB_I2C/rkv_i2c_tb/sim/out/obj/rkv_i2c_tb.simv.daidir/.stitch_so_list -o out/obj/rkv_i2c_tb.simv csrc/topshell_partcomp.v 


	@echo Done Verilog partition compilations

